data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, as.is=TRUE)
data$datetime<-strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
mydata<-subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
png(file = "plot3.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
plot(mydata$datetime,as.numeric(mydata$Sub_metering_1),type="n", ylab="Energy sub metering", xlab="")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_1), type="l", col="black")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_2), type="l", col="red")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_3), type="l", col="blue")
legend("topright", lty = 1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
