data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, as.is=TRUE)
data$datetime<-strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
mydata<-subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
png(file = "plot4.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
par(mfrow=c(2,2))
plot(mydata$datetime, as.numeric(mydata$Global_active_power), type="n", ylab="Global Active Power (kilowatts)", xlab="")
lines(mydata$datetime, as.numeric(mydata$Global_active_power), type="l")
plot(mydata$datetime, as.numeric(mydata$Voltage), type="n", ylab="Voltage", xlab="datetime")
lines(mydata$datetime, as.numeric(mydata$Voltage), type="l")
plot(mydata$datetime,as.numeric(mydata$Sub_metering_1),type="n", ylab="Energy sub metering", xlab="")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_1), type="l", col="black")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_2), type="l", col="red")
lines(mydata$datetime, as.numeric(mydata$Sub_metering_3), type="l", col="blue")
legend("topright", lty = 1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(mydata$datetime, as.numeric(mydata$Global_reactive_power), type="n", ylab="Global_reactive_power", xlab="datetime")
lines(mydata$datetime, as.numeric(mydata$Global_reactive_power), type="l")
dev.off()
