data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, as.is=TRUE)
data$datetime<-strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
mydata<-subset(data, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
png(file = "plot1.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white")
hist(as.numeric(mydata$Global_active_power), col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
